server:
  port: ${PORT:8080}
logging:
  level.org.atmosphere: warn
spring:
  application:
    name: vaadin-starter
  mustache:
    check-template-location: false

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
